export const PLAYERS_SEED = [
  { name: 'Okky', class: 'B', note: '' },
  { name: 'Elvin', class: 'B', note: '' },
  { name: 'Christy', class: 'C', note: '' },
  { name: 'Arga', class: 'B', note: '' },
  { name: 'Ivan', class: 'A', note: '' },
  { name: 'Mei', class: 'C', note: '' },
  { name: 'Ricky V.', class: 'B', note: '' },
  { name: 'Hendra Lim', class: 'S', note: '' },
  { name: 'Frengky', class: 'A', note: '' },
  { name: 'Erick MLP', class: 'B', note: '' },
  { name: 'Ricardo', class: 'B', note: '' },
  { name: 'Wido', class: 'A', note: '' },
  { name: 'Saputra', class: 'S', note: '' },
  { name: 'Kelvinsen', class: 'S', note: '' },
  { name: 'Benny', class: 'B', note: '' },
  { name: 'Norys', class: 'A', note: '' },
  { name: 'Deki', class: 'S', note: '' },
  { name: 'Erwin', class: 'A', note: '' },
];
